datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-host:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
