services:
  apache:
    image: httpd:alpine
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - apache-logs:/usr/local/apache2/logs
    ports:
      - 9040:80

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx
    ports:
      - 80:80
    
  promtail:
    image: grafana/promtail:main
    volumes:
      - ./promtail-conf.yml:/etc/promtail/config.yml
      - nginx-logs:/var/log/nginx
      - apache-logs:/usr/local/apache2/logs

  node-exporter:
    image: bitnami/node-exporter:1.9.1
    ports:
      - 9100:9100

volumes:
  nginx-logs:
  apache-logs:
