global: 
  scrape_interval: 15s
  scrape_timeout: 10s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - "localhost:9090"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: 'localhost.*'
        replacement: 'prometheus-host'
