services:
  apache:
    image: 8ct8pus/apache-php-fpm-alpine:2.4.2

  nginx:
    build: ./nginx/
    volumes:
      - nginx-logs:/var/log/nginx/
    ports:
      - 80:8090
    links:
      - apache:apache-server
    depends_on:
      - apache
    
  logs:
    build: ./logs/
    volumes:
      - nginx-logs:/var/log/nginx/
    depends_on:
      - nginx
    command: sh -c "python /var/scripts/logs.py"

volumes:
  nginx-logs: