services:
  apache:
    image: asadkrmv/trainee-apache

  nginx:
    build: asadkrmv/trainee-nginx
    volumes:
      - nginx-logs:/var/log/nginx/
    ports:
      - 80:8090
    links:
      - apache:apache-server
    depends_on:
      - apache
    
  logs:
    build: asadkrmv/trainee-nginx-logs
    volumes:
      - nginx-logs:/var/log/nginx/
    depends_on:
      - nginx
    command: sh -c "python /var/scripts/logs.py"

volumes:
  nginx-logs: