apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
namespace: dev

labels:
- includeSelectors: true
  pairs:
    env: dev
  
patches:
  - path: nginx-service.yml
    target:
      kind: Service
      name: nginx-service
  - path: configMap.yml
    target:
      kind: ConfigMap
      name: nginx-html