global: 
  scrape_interval: 15s
  scrape_timeout: 10s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: 'localhost.*'
        replacement: 'prometheus-host'
        
  - job_name: "trainee-targets"
    static_configs:
      - targets:
        - "16.171.0.85:9100"
        - "16.171.18.76:9100"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '16.171.0.85.*'
        replacement: 'memory-server'
      - source_labels: [__address__]
        target_label: instance
        regex: '16.171.18.76.*'
        replacement: 'cpu-server'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets: ["alertmanager:9093"]    